### ISSUE TITLE
Validator tries to find libpoh-simd.so in the wrong directory

### ISSUE THREAD

**Issue by Vovans** [im-0/fedora-rpm.solana#1]
Validator tries to find the library in /opt/solana/testnet/libexec/perf-libs, but there is no such directory

[2022-01-22T17:09:44.976129692Z INFO  solana_entry::entry] Loading "libpoh-simd.so"
[2022-01-22T17:09:44.976175918Z WARN  solana_perf::perf_libs] "/opt/solana/testnet/libexec/perf-libs" does not exist

The library is located in /opt/solana/testnet/bin/perf-libs/. Here it is [created](https://github.com/im-0/fedora-rpm.solana-perf-libs/blob/1ba177113928dc63538e0e82accea6873936c52a/solana-perf-libs-testnet.spec#L30-L31)

`%install
mkdir -p %{buildroot}/opt/solana/%{solana_suffix}/bin/perf-libs`

**Comment by im-0** [comment]
Спасибо! Поломал, когда добавил враппер для "правильной" загрузки с jemalloc. Позже сегодня починю.

**Comment by im-0** [comment]
Fixed in https://github.com/im-0/fedora-rpm.solana/commit/f92df51a3a0bb1500982310e7155f61c5eac2f80 and https://github.com/im-0/fedora-rpm.solana/commit/3a25f22f39fdd455540f8fccc97999fd23540722

It seems that on 5950x it makes no difference as PoH occupies whole dedicated thread anyway.
